export const skillSetData =  [
  "Search Engine Optimization", "Strategic Planning", "Natural Language Processing",
  "System Analysis", "User Research", "Budgeting and Forecasting", "Troubleshooting",
  "Data Mining", "Information Science", "Knowledge Management", "iOS development",
  "Interaction Design", "Computer Science", "UX Writing", "Network Architecture",
  "Project Management", "Business Analysis", "Database Security", "Machine Learning",
  "Database Management", "Information Architecture", "Artificial Intelligence",
  "Product Development", "Web Development", "UX/UI Design", "Agile Methodologies",
  "Information Systems", "Systems Administration", "SAS", "Communication",
  "Customer Experience", "Networking", "Negotiation", "Research", "Wireframe and Prototyping",
  "Coding", "Visual Design", "R", "Network Administration", "Data Modeling", "Java", "CSS",
  "Decision Making", "Marketing", "Cloud Services", "Social Media Marketing",
  "Organizational Skills", "User Experience Design", "JavaScript", "Cyber Security",
  "Data Analysis", "Network hardware configuration", "Scripting language (Python)",
  "Adobe Creative Suite", "Microsoft Excel", "Computer Networking", "Content Management",
  "Leadership", "Usability Testing", "Graphic Design", "C++", "Data Visualization",
  "UI/UX design", "Unix/Linux Systems", "Scripting languages", "Cloud Computing",
  "Decision-Making", "Financial Planning", "Swift", "Information Technology",
  "Data Science", "English", "HTML/CSS", "Infrastructure as Code (IAC)",
  "Product Marketing", "HTML", "Negotiation Techniques", "Continuous Integration/Continuous Delivery (CI/CD)",
  "Technical Understanding", "Technical Writing", "Performance Tuning",
  "Android development", "ER Studio", "MS Project", "Linux", "Time Management",
  "Information Technology Infrastructure Library (ITIL)", "Cross-Functional Team Leadership",
  "Programming Languages", "Operating Systems", "Team Leadership", "Python Programming",
  "Cyber Security protocols", "Product Lifecycle Management", "Software Development",
  "Network software management", "Oracle", "SQL", "Risk Management", "Communication Skills",
  "Human-Computer Interaction", "R programming", "Market Research",
  "Problem Solving", "Business Strategy", "Python", "System Administration", "Profession"
];